export const ROLE_ROUTES = {
  SUPER_ADMIN: ["dashboard","employees","departments","attendance","leave","payroll","recruitment","onboarding","performance","assets","helpdesk","lms","analytics","settings","calendar","documents","exit","shifts","orgchart"],
  ADMIN:       ["dashboard","employees","departments","attendance","leave","payroll","recruitment","onboarding","performance","assets","helpdesk","lms","analytics","settings","calendar","documents","exit","shifts","orgchart"],
  HR:          ["dashboard","employees","departments","attendance","leave","recruitment","onboarding","performance","lms","analytics","calendar","documents","exit","shifts","orgchart"],
  MANAGER:     ["dashboard","employees","attendance","leave","performance","lms","calendar","orgchart","shifts"],
  FINANCE:     ["dashboard","payroll","analytics","settings","documents"],
  EMPLOYEE:    ["dashboard","attendance","leave","lms","calendar"],
};

export const ROLE_SIDEBAR = {
  SUPER_ADMIN: [
    { id: "dashboard",   label: "Dashboard",   icon: "IconLayoutDashboard"   },
    { id: "employees",   label: "Employees",   icon: "IconUsers"             },
    { id: "departments", label: "Departments", icon: "IconBuildingCommunity" },
    { id: "orgchart",    label: "Org Chart",   icon: "IconHierarchy"         },
    { id: "attendance",  label: "Attendance",  icon: "IconClock"             },
    { id: "shifts",      label: "Shifts",      icon: "IconRotateClockwise"       },
    { id: "leave",       label: "Leave",       icon: "IconCalendarOff"       },
    { id: "calendar",    label: "Calendar",    icon: "IconCalendar"          },
    { id: "payroll",     label: "Payroll",     icon: "IconCurrencyRupee"     },
    { id: "recruitment", label: "Recruitment", icon: "IconBriefcase"         },
    { id: "onboarding",  label: "Onboarding",  icon: "IconUserPlus"          },
    { id: "performance", label: "Performance", icon: "IconTarget"            },
    { id: "documents",   label: "Documents",   icon: "IconFolder"            },
    { id: "exit",        label: "Exit Mgmt",   icon: "IconDoorExit"          },
    { id: "assets",      label: "Assets",      icon: "IconPackage"           },
    { id: "helpdesk",    label: "Helpdesk",    icon: "IconLifebuoy"          },
    { id: "lms",         label: "Learning",    icon: "IconBook"              },
    { id: "analytics",   label: "Analytics",   icon: "IconChartBar"          },
    { id: "settings",    label: "Settings",    icon: "IconSettings"          },
  ],
  ADMIN: [
    { id: "dashboard",   label: "Dashboard",   icon: "IconLayoutDashboard"   },
    { id: "employees",   label: "Employees",   icon: "IconUsers"             },
    { id: "departments", label: "Departments", icon: "IconBuildingCommunity" },
    { id: "orgchart",    label: "Org Chart",   icon: "IconHierarchy"         },
    { id: "attendance",  label: "Attendance",  icon: "IconClock"             },
    { id: "shifts",      label: "Shifts",      icon: "IconRotateClockwise"       },
    { id: "leave",       label: "Leave",       icon: "IconCalendarOff"       },
    { id: "calendar",    label: "Calendar",    icon: "IconCalendar"          },
    { id: "payroll",     label: "Payroll",     icon: "IconCurrencyRupee"     },
    { id: "recruitment", label: "Recruitment", icon: "IconBriefcase"         },
    { id: "onboarding",  label: "Onboarding",  icon: "IconUserPlus"          },
    { id: "performance", label: "Performance", icon: "IconTarget"            },
    { id: "documents",   label: "Documents",   icon: "IconFolder"            },
    { id: "exit",        label: "Exit Mgmt",   icon: "IconDoorExit"          },
    { id: "assets",      label: "Assets",      icon: "IconPackage"           },
    { id: "helpdesk",    label: "Helpdesk",    icon: "IconLifebuoy"          },
    { id: "lms",         label: "Learning",    icon: "IconBook"              },
    { id: "analytics",   label: "Analytics",   icon: "IconChartBar"          },
    { id: "settings",    label: "Settings",    icon: "IconSettings"          },
  ],
  HR: [
    { id: "dashboard",   label: "Dashboard",   icon: "IconLayoutDashboard"   },
    { id: "employees",   label: "Employees",   icon: "IconUsers"             },
    { id: "departments", label: "Departments", icon: "IconBuildingCommunity" },
    { id: "orgchart",    label: "Org Chart",   icon: "IconHierarchy"         },
    { id: "attendance",  label: "Attendance",  icon: "IconClock"             },
    { id: "shifts",      label: "Shifts",      icon: "IconRotateClockwise"       },
    { id: "leave",       label: "Leave",       icon: "IconCalendarOff"       },
    { id: "calendar",    label: "Calendar",    icon: "IconCalendar"          },
    { id: "recruitment", label: "Recruitment", icon: "IconBriefcase"         },
    { id: "onboarding",  label: "Onboarding",  icon: "IconUserPlus"          },
    { id: "performance", label: "Performance", icon: "IconTarget"            },
    { id: "documents",   label: "Documents",   icon: "IconFolder"            },
    { id: "exit",        label: "Exit Mgmt",   icon: "IconDoorExit"          },
    { id: "lms",         label: "Learning",    icon: "IconBook"              },
    { id: "analytics",   label: "Analytics",   icon: "IconChartBar"          },
  ],
  MANAGER: [
    { id: "dashboard",   label: "Dashboard",   icon: "IconLayoutDashboard"   },
    { id: "employees",   label: "My Team",     icon: "IconUsers"             },
    { id: "orgchart",    label: "Org Chart",   icon: "IconHierarchy"         },
    { id: "attendance",  label: "Attendance",  icon: "IconClock"             },
    { id: "shifts",      label: "Shifts",      icon: "IconRotateClockwise"       },
    { id: "leave",       label: "Leave",       icon: "IconCalendarOff"       },
    { id: "calendar",    label: "Calendar",    icon: "IconCalendar"          },
    { id: "performance", label: "Performance", icon: "IconTarget"            },
    { id: "lms",         label: "Learning",    icon: "IconBook"              },
  ],
  FINANCE: [
    { id: "dashboard",   label: "Dashboard",   icon: "IconLayoutDashboard"   },
    { id: "payroll",     label: "Payroll",     icon: "IconCurrencyRupee"     },
    { id: "documents",   label: "Documents",   icon: "IconFolder"            },
    { id: "analytics",   label: "Analytics",   icon: "IconChartBar"          },
    { id: "settings",    label: "Settings",    icon: "IconSettings"          },
  ],
  EMPLOYEE: [
    { id: "dashboard",   label: "Dashboard",    icon: "IconLayoutDashboard"  },
    { id: "attendance",  label: "My Attendance", icon: "IconClock"           },
    { id: "leave",       label: "My Leave",     icon: "IconCalendarOff"      },
    { id: "calendar",    label: "Calendar",     icon: "IconCalendar"         },
    { id: "lms",         label: "Learning",     icon: "IconBook"             },
  ],
};

export const ROLE_LABELS = {
  SUPER_ADMIN: "Super Admin",
  ADMIN:       "Administrator",
  HR:          "HR Manager",
  MANAGER:     "Team Manager",
  FINANCE:     "Finance Admin",
  EMPLOYEE:    "Employee",
};

export const ROLE_COLORS = {
  SUPER_ADMIN: { bg: "#fef3c7", text: "#d97706" },
  ADMIN:       { bg: "#dbeafe", text: "#2563eb" },
  HR:          { bg: "#f3e8ff", text: "#7c3aed" },
  MANAGER:     { bg: "#dcfce7", text: "#16a34a" },
  FINANCE:     { bg: "#fce7f3", text: "#be185d" },
  EMPLOYEE:    { bg: "#f1f5f9", text: "#475569" },
};
